# Generated by Django 3.2.6 on 2021-08-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('true_answer', models.CharField(max_length=100)),
                ('studentPoints', models.FloatField(choices=[(0.25, 'D = 0.25'), (0.5, 'C = 0.5'), (0.75, 'B = 0.75'), (1.0, 'A = 1.00')], max_length=3)),
            ],
        ),
    ]
