# Generated by Django 3.2.4 on 2021-08-28 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOFlesson', models.CharField(max_length=15)),
                ('slug', models.SlugField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('family', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='desinDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
