# Generated by Django 3.2.4 on 2021-08-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210828_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='lessonName',
            field=models.CharField(default='null', max_length=15),
        ),
    ]
