# Generated by Django 3.2.4 on 2021-08-28 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_lessonname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='desinDate',
            new_name='desineDate',
        ),
    ]
