# Generated by Django 3.2.4 on 2021-08-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_rename_desindate_question_desinedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='published',
            field=models.CharField(choices=[('P', 'published'), ('N', 'Not published')], default='P', max_length=1),
        ),
    ]
